### ISSUE TITLE
Uncaught TypeError: Cannot read property 'childrenIds' of undefined

### ISSUE THREAD

**Issue by gbevan** [jccguimaraes/project-viewer-plus#46]
Hi, getting error when creating my first group:

1. New install of project-view-plus
2. Add Group/Project
3. enter Name and select Icon
4. Click Save, get this error. Group not saved

**Atom**: 1.39.1 x64
**Electron**: 3.1.10
**OS**: Ubuntu 18.04.2
**Thrown From**: [project-viewer-plus](https://github.com/jccguimaraes/project-viewer-plus) package 0.0.4

### Stack Trace

Uncaught TypeError: Cannot read property 'childrenIds' of undefined

```
At /home/bev/.atom/packages/project-viewer-plus/dist/services/state.js:216

TypeError: Cannot read property 'childrenIds' of undefined
    at State.addEntry (/packages/project-viewer-plus/dist/services/state.js:216:12)
    at EditorContainer.handleChangeAction (/packages/project-viewer-plus/dist/containers/editor.js:45:23)
    at /packages/project-viewer-plus/dist/containers/editor.js:237:36)
    at EditorOptions.onDidClick (/packages/project-viewer-plus/dist/components/editor/options.js:17:10)
    at EditorOptions.click (/packages/project-viewer-plus/dist/components/editor/options.js:86:31)
```

### Commands

```
     -0:15.1.0 project-viewer-plus:add-entry (ul.list-tree.has-collapsable-children)
```

### Non-Core Packages

```
api-workbench 0.8.48 
atom-beautify 0.33.4 
atom-drawio 1.15.0 
atom-html-templates 0.1.3 
atom-ide-ui 0.13.0 
atom-mermaid 3.3.1 
busy-signal 2.0.1 
color-picker 2.3.0 
color-tabs-byproject 1.3.0 
file-icons 2.1.33 
file-types 1.0.1 
git-plus 8.7.1 
git-plus-toolbar 1.0.1 
go-debug 1.6.2 
go-plus 6.1.0 
go-signature-statusbar 1.2.3 
ide-python 1.4.1 
indent-guide-improved 1.4.13 
intentions 1.1.5 
language-docker 1.1.8 
language-hcl 0.4.0 
language-mermaid 0.6.0 
linter 2.3.0 
linter-coffeescript 1.0.0 
linter-docker 0.3.2 
linter-eslint 8.5.5 
linter-htmlhint 1.6.2 
linter-tslint 1.10.28 
linter-ui-default 1.7.1 
MagicPython 1.1.1 
markdown-preview-enhanced 0.16.3 
platformio-ide-terminal 2.9.1 
project-viewer-plus 0.0.4 
python-indent 1.2.3 
tabs-to-spaces 1.0.5 
tool-bar 1.1.11 
underline-trailing-whitespace 1.4.2 
```

**Comment by jccguimaraes** [comment]
hey @gbevan,

Thank you for trying this package even in its early development. 
The development is slow but not dead.

I will address this issue and on next "alpha" release, it will be fix, hopefully :)

**Comment by jccguimaraes** [comment]
@gbevan can you check the new patch?

**Comment by gbevan** [comment]
Thats working fine thx

**Comment by jccguimaraes** [comment]
great news! thanks
